#!/bin/bash

### BEGIN INIT INFO
# Provides:          unicorn_{{app}}
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server for {{app}
# Description:       starts unicorn for {{app}}
### END INIT INFO

APP={{app}}
HOST={{host}}
PORT={{port}}
DAEMON=unicorn
APPDIR={{app_dir}}
DAEMON_OPTS="-c {{config}} -E production -D -l {{host}}:{{port}}"
NAME="unicorn_$APP"
DESC="Unicorn for $APP"
PID={{pid}}

case "$1" in
  start)
        CD_TO_APP_DIR="cd $APPDIR"
        START_DAEMON_PROCESS="bundle exec $DAEMON $DAEMON_OPTS"

        echo -n "Starting $DESC: "
	$CD_TO_APP_DIR > /dev/null 2>&1 && $START_DAEMON_PROCESS
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
        echo "$NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        kill -USR2 `cat $PID`
        echo "$NAME."
        ;;
  reload)
        echo -n "Reloading $DESC configuration: "
        kill -HUP `cat $PID`
        echo "$NAME."
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart|reload}" >&2
        exit 1
        ;;
esac

exit 0
